<?php

namespace Database\Seeders;

use App\Models\TrackingItem;
use Illuminate\Database\Seeder;

/**
 * Data Dev Tracker (Jubelio + Epik + Omnichannel) — di-embed langsung di seeder.
 * Dibangkitkan otomatis dari `dist (2).yaml` via scripts/gen_tracking_json.py.
 * JANGAN edit manual; regenerate bila spec berubah. Total: 342 item.
 *
 * Idempotent: item baru di-insert; status/notes/pic hasil edit user TIDAK ditimpa.
 */
class TrackingItemsSeeder extends Seeder
{
    public function run(): void
    {
        $created = 0;
        $updated = 0;

        foreach ($this->items() as $row) {
            $item = TrackingItem::firstOrNew([
                'method' => $row['method'],
                'endpoint' => $row['endpoint'],
            ]);

            // Metadata selalu disinkronkan dari sumber dokumen.
            $item->domain = $row['domain'];
            $item->function_id = $row['function_id'];
            $item->baseline_status = $row['status'];
            $item->priority = $row['priority'];
            $item->source = $row['source'];

            if (! $item->exists) {
                $item->status = $row['status'];
                $item->pic = $row['pic'];
                $created++;
            } else {
                $updated++; // JANGAN timpa status/notes/pic yang sudah diedit.
            }

            $item->save();
        }

        $this->command?->info("TrackingItems: +$created baru, $updated diperbarui (metadata).");
    }

    /** @return array<int,array<string,?string>> */
    private function items(): array
    {
        return [
            ['domain'=>'Region','method'=>'GET','endpoint'=>'/region/provinces','function_id'=>'Ambil daftar provinsi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Region','method'=>'GET','endpoint'=>'/region/subdistricts/?district_id={district_id}','function_id'=>'Ambil daftar kelurahan per kecamatan','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Region','method'=>'GET','endpoint'=>'/region/cities/?province_id={province_id}','function_id'=>'Ambil daftar kota per provinsi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Region','method'=>'GET','endpoint'=>'/region/districts/?city_id={city_id}','function_id'=>'Ambil daftar kecamatan per kota','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/reserved/','function_id'=>'Buat reservasi stok item','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/reserved/','function_id'=>'Ambil daftar stok yang direservasi','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/reserved/{id}','function_id'=>'Ambil detail reservasi stok','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/to-stock/{location_id}','function_id'=>'Ambil item untuk distok per lokasi','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'GET','endpoint'=>'/systemsetting/sales-return-setting','function_id'=>'Ambil setting retur penjualan','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'POST','endpoint'=>'/systemsetting/sales-return-setting','function_id'=>'Buat setting retur penjualan','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'GET','endpoint'=>'/wms/default-bin/{location_id}','function_id'=>'Ambil bin default per lokasi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/couriers','function_id'=>'Ambil daftar kurir WMS','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/shipments/{courier_new_id}','function_id'=>'Ambil shipment per kurir tertentu','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/shipments/instant/all','function_id'=>'Ambil semua jadwal shipment kurir instant','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/scan-shipment','function_id'=>'Ambil jadwal shipment via scan nomor shipment','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/shipments/','function_id'=>'Buat jadwal shipment kurir reguler','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/picklists/change-picker/','function_id'=>'Ganti staf picker','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/shipment-detail/','function_id'=>'Tambah order ke jadwal shipment','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/shipments/instant-courier/','function_id'=>'Buat jadwal shipment kurir instant','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/orders/ready-to-pick/','function_id'=>'Ambil order siap dipick','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/shipments/completed/{shipment_type}/{courierIds}','function_id'=>'Ambil shipment yang sudah dalam pengiriman','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/shipped/','function_id'=>'Ambil order yang sudah dikirim kurir','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/orders/empty-stock/','function_id'=>'Ambil order yang stoknya kosong','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/picklists/confirm-pick/','function_id'=>'Ambil order yang sedang proses picking','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/shipments/all','function_id'=>'Ambil semua jadwal shipment kurir reguler','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/order/ready-to-ship','function_id'=>'Ambil order yang perlu dikirim ke kurir','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/packlists/finish-pack/','function_id'=>'Ambil order yang selesai packing','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/packlist/scan-order','function_id'=>'Ambil daftar item untuk dipacking','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/ready-to-process','function_id'=>'Pindahkan order ke status \'ready to process\'','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/shipments/orders/','function_id'=>'Ambil AWB untuk order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/ready-to-pick','function_id'=>'Pindahkan order ke status \'ready to pick\'','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/orders/request-cancel/','function_id'=>'Ambil order yang diminta batal oleh customer','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/orders/failed-pick','function_id'=>'Ambil order yang batal dipick','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/orders/finish-pick/','function_id'=>'Ambil order yang selesai dipick','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/orders/completed/','function_id'=>'Ambil order selesai dari semua channel','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/received/author','function_id'=>'Tugaskan staf untuk putaway','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/packlist/update-qty-packed','function_id'=>'Perbarui qty item yang sudah dipacking','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/packlist/verify-barcode/','function_id'=>'Verifikasi item/SKU/barcode/serial/batch','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/packlist/mark-as-complete/','function_id'=>'Tandai order siap kirim (selesai packing)','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/packlists/process/','function_id'=>'Ambil order yang sedang proses packing','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/employee/{NIKorEmail}','function_id'=>'Ambil info staf gudang per NIK/email','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'GET','endpoint'=>'/wms/sales/orders/ready-to-process/','function_id'=>'Ambil order siap diproses','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Journal','method'=>'GET','endpoint'=>'/accounts/lookup/all','function_id'=>'Ambil daftar akun (Chart of Accounts)','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'GET','endpoint'=>'/blibli/pickupPoints','function_id'=>'Ambil titik pickup Blibli','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Cash & Bank','method'=>'GET','endpoint'=>'/cashbank/payments/','function_id'=>'Ambil daftar pembayaran kas/bank (uang keluar)','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Cash & Bank','method'=>'GET','endpoint'=>'/cashbank/payments/id','function_id'=>'Ambil detail satu pembayaran kas/bank','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Cash & Bank','method'=>'GET','endpoint'=>'/cashbank/receives','function_id'=>'Ambil daftar penerimaan kas/bank (uang masuk)','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Cash & Bank','method'=>'GET','endpoint'=>'/cashbank/receives/id','function_id'=>'Ambil detail satu penerimaan kas/bank','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'GET','endpoint'=>'/contact/category/','function_id'=>'Ambil daftar kategori kontak','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'GET','endpoint'=>'/contacts/','function_id'=>'Ambil semua kontak','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'POST','endpoint'=>'/contacts/','function_id'=>'Buat/ubah kontak','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'DELETE','endpoint'=>'/contacts/','function_id'=>'Hapus kontak','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'GET','endpoint'=>'/contacts/{id}','function_id'=>'Ambil detail satu kontak','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'GET','endpoint'=>'/contacts/customers-suppliers/','function_id'=>'Ambil kontak yang sekaligus customer & supplier','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'GET','endpoint'=>'/contacts/customers/','function_id'=>'Ambil daftar customer','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Contact','method'=>'GET','endpoint'=>'/contacts/suppliers/','function_id'=>'Ambil daftar supplier/vendor','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Couriers','method'=>'GET','endpoint'=>'/couriers','function_id'=>'Ambil semua kurir','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Couriers','method'=>'GET','endpoint'=>'/couriers/{id}','function_id'=>'Ambil detail satu kurir','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Couriers','method'=>'GET','endpoint'=>'/couriers/tenant/{id}','function_id'=>'Ambil kurir milik tenant tertentu','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/','function_id'=>'Ambil stok semua produk','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/group/merge-catalog','function_id'=>'Gabungkan item serupa dalam katalog','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/putaway/all','function_id'=>'Ambil ID putaway','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/putaway/not-start','function_id'=>'Daftar putaway yang belum dimulai','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/putaway/processed','function_id'=>'Daftar putaway yang sedang diproses','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/putaway/completed','function_id'=>'Daftar putaway yang sudah selesai','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/received/item/{putaway_id}','function_id'=>'Ambil daftar item putaway','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/to-buy','function_id'=>'Ambil daftar produk yang perlu dibeli (untuk PO)','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/activity/','function_id'=>'Ambil riwayat pergerakan stok produk','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/adjustments/','function_id'=>'Ambil semua penyesuaian stok','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/adjustments/','function_id'=>'Buat/ubah penyesuaian stok','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'DELETE','endpoint'=>'/inventory/adjustments/','function_id'=>'Hapus dokumen penyesuaian stok','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/adjustments/{id}','function_id'=>'Ambil detail penyesuaian stok','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/catalog/','function_id'=>'Buat/ubah produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/catalog/{group_id}','function_id'=>'Ambil katalog item per grup','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'GET','endpoint'=>'/inventory/catalog/for-listing/{id}','function_id'=>'Ambil data produk untuk listing channel','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'POST','endpoint'=>'/inventory/catalog/listing','function_id'=>'Buat/ubah listing produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'POST','endpoint'=>'/inventory/catalog/upload','function_id'=>'Unggah listing produk ke channel','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/{channel_id}/store-categories/{store_id}','function_id'=>'Ambil kategori toko per channel','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/{id}/attributes-value/','function_id'=>'Ambil nilai atribut kategori','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/{id}/attributes/','function_id'=>'Ambil atribut kategori','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/{id}/variations/','function_id'=>'Ambil varian kategori','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/category-map/{id}','function_id'=>'Ambil pemetaan kategori ke marketplace','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'GET','endpoint'=>'/inventory/categories/channel-categories/{parent_id}','function_id'=>'Ambil kategori channel','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/item-categories/','function_id'=>'Ambil semua kategori','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/categories/item-categories/information/{id}/','function_id'=>'Ambil informasi kategori','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/catalog/set-master','function_id'=>'Set produk dari \'In Review\' menjadi \'Master\'','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/received/putaway','function_id'=>'Letakkan item ke rak (putaway)','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/received/finish-putaway','function_id'=>'Tandai proses putaway selesai','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/to-stock/','function_id'=>'Ambil semua item yang stoknya perlu disesuaikan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/to-sales-return','function_id'=>'Ambil daftar item retur penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/by-transfer/{item_transfer_id}','function_id'=>'Ambil daftar produk yang akan diterima per nomor transfer','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/item-bundles/','function_id'=>'Ambil semua bundle produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/','function_id'=>'Ambil semua grup produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'DELETE','endpoint'=>'/inventory/items/','function_id'=>'Hapus produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/items/','function_id'=>'Buat/ubah bundle produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/{id}','function_id'=>'Ambil detail produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/items/archive/','function_id'=>'Arsipkan produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/archived/','function_id'=>'Ambil semua produk terarsip','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/received','function_id'=>'Ambil daftar item yang sudah diterima','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/{id}/batch-number','function_id'=>'Ambil nomor batch item','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/items/restore/','function_id'=>'Pulihkan produk dari arsip','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/items/all-stocks/','function_id'=>'Ambil stok produk per banyak ID','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/split-item','function_id'=>'Pisah item (split) jadi unit lebih kecil','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/by-invoice/{invoice_id}','function_id'=>'Ambil daftar item per nomor invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/by-sku/{sku}','function_id'=>'Ambil produk per SKU','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/channel-category-attributes/','function_id'=>'Ambil semua atribut kategori channel','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/channel-category-tree/','function_id'=>'Ambil pohon kategori channel','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/inventory/items/complete-return/','function_id'=>'Set item jadi tidak diretur (batal retur)','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'DELETE','endpoint'=>'/inventory/items/item-variant/','function_id'=>'Hapus varian item','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'GET','endpoint'=>'/inventory/items/errors/','function_id'=>'Ambil daftar listing yang gagal upload','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/group/{id}','function_id'=>'Ambil grup produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/items/prices/','function_id'=>'Ambil harga produk per banyak ID','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/inventory/items/reject-return/','function_id'=>'Tolak permintaan retur','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/reviews/','function_id'=>'Ambil semua produk dalam status review','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/items/masters','function_id'=>'Ambil semua produk master','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/to-adjust/','function_id'=>'Ambil cost & stok item untuk penyesuaian','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/inventory/items/to-return/','function_id'=>'Terima retur penjualan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/to-sell/{location_id}','function_id'=>'Ambil item yang bisa dijual per lokasi','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/floors','function_id'=>'Ambil lokasi rak per lantai','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/rows','function_id'=>'Ambil lokasi rak per baris','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/columns','function_id'=>'Ambil lokasi rak per kolom','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/stock-opname','function_id'=>'Buat daftar item untuk diopname','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname','function_id'=>'Ambil daftar stock opname semua status','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/{opname_header_id}','function_id'=>'Ambil stok real-time saat opname berjalan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/bins','function_id'=>'Ambil semua bin per lokasi','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/items','function_id'=>'Ambil semua item untuk diopname','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/stock-opname/finalize','function_id'=>'Selesaikan opname & push stok final','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/need-restock/','function_id'=>'Ambil produk yang perlu restock','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/out-of-stock-in-order/','function_id'=>'Ambil produk habis stok yang ada di order','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/internal-price-list/','function_id'=>'Ambil semua harga produk (price list internal)','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/price-list/','function_id'=>'Ubah harga produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/promotions/','function_id'=>'Ambil semua promosi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/promotions/','function_id'=>'Buat promosi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'DELETE','endpoint'=>'/inventory/promotions/','function_id'=>'Hapus promosi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/promotions/{id}','function_id'=>'Ambil detail promosi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/stock-opname/items/filtered','function_id'=>'Ambil item opname terfilter per lokasi rak','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/revaluations/','function_id'=>'Buat/ubah penyesuaian nilai (revaluasi) stok','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/inventory/search-brands/','function_id'=>'Ambil semua merek (brand)','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/transfer/mark-printed','function_id'=>'Tandai transfer item sudah dicetak','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/transfers/','function_id'=>'Buat transfer stok (masuk/keluar)','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'DELETE','endpoint'=>'/inventory/transfers/','function_id'=>'Hapus transfer stok','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfers/{id}','function_id'=>'Ambil detail transfer stok','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfers/in','function_id'=>'Ambil transfer stok masuk','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfers/all-transit','function_id'=>'Ambil semua nomor transaksi transfer transit','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfers/out','function_id'=>'Ambil transfer stok keluar','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfers/out-finished','function_id'=>'Ambil transfer yang sudah selesai/diterima','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfers/transit','function_id'=>'Ambil transfer stok dalam perjalanan (transit)','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/transfer/delivery','function_id'=>'Cetak laporan surat jalan transfer','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'POST','endpoint'=>'/inventory/upload-image','function_id'=>'Unggah gambar produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/by-bill/{doc_id}','function_id'=>'Ambil detail item retur pembelian per bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'POST','endpoint'=>'/inventory/items/received/auto-putaway','function_id'=>'Set item untuk auto-putaway','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Inventory','method'=>'GET','endpoint'=>'/inventory/items/item-on-stock','function_id'=>'Ambil daftar item untuk ditransfer','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Journal','method'=>'GET','endpoint'=>'/journal/','function_id'=>'Ambil semua jurnal','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Journal','method'=>'GET','endpoint'=>'/journal/{id}','function_id'=>'Ambil detail jurnal per ID','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Journal','method'=>'GET','endpoint'=>'/journal/manual-journal/','function_id'=>'Ambil semua jurnal manual','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Journal','method'=>'POST','endpoint'=>'/journal/manual-journal/','function_id'=>'Buat/ubah jurnal manual','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/lazada/get-document/','function_id'=>'Cetak invoice/label Lazada','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'GET','endpoint'=>'/locations/','function_id'=>'Ambil semua lokasi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'POST','endpoint'=>'/locations/','function_id'=>'Buat/ubah lokasi & denah rak','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'DELETE','endpoint'=>'/locations/','function_id'=>'Hapus lokasi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'GET','endpoint'=>'/locations/{id}','function_id'=>'Ambil detail lokasi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'GET','endpoint'=>'/locations/bin/{location_id}','function_id'=>'Ambil bin per lokasi','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'GET','endpoint'=>'/locations/pos','function_id'=>'Ambil lokasi yang punya outlet POS','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Location & The Rack Plan','method'=>'GET','endpoint'=>'/locations/store/','function_id'=>'Ambil pemetaan lokasi ke toko','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Authentication','method'=>'POST','endpoint'=>'/login','function_id'=>'Login & dapatkan token akses (Sanctum)','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Channels','method'=>'GET','endpoint'=>'/marketplace/store/','function_id'=>'Ambil semua toko marketplace yang terhubung','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'DELETE','endpoint'=>'/purchase/','function_id'=>'Hapus retur pembelian','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/bills/','function_id'=>'Ambil semua bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/bills/','function_id'=>'Buat/ubah bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'DELETE','endpoint'=>'/purchase/bills/','function_id'=>'Hapus bill (tagihan pembelian)','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/bills/for-return','function_id'=>'Ambil nomor bill untuk diretur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/bills/{id}','function_id'=>'Ambil detail bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/bills/overdue/','function_id'=>'Ambil bill yang jatuh tempo','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/bills/unpaid/','function_id'=>'Ambil bill yang belum lunas','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/orders/','function_id'=>'Ambil semua purchase order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/orders/','function_id'=>'Buat/ubah purchase order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'DELETE','endpoint'=>'/purchase/orders/','function_id'=>'Hapus purchase order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/orders/{id}','function_id'=>'Ambil detail purchase order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/orders/progress','function_id'=>'Ambil progres penerimaan semua PO','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/payments/','function_id'=>'Ambil semua pembayaran bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/payments/','function_id'=>'Buat/ubah pembayaran bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'DELETE','endpoint'=>'/purchase/payments/','function_id'=>'Hapus pembayaran bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/payments/{id}','function_id'=>'Ambil detail pembayaran bill','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/purchase-returns/','function_id'=>'Ambil semua retur pembelian','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/purchase-returns/','function_id'=>'Buat/ubah retur pembelian','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/serial-number/mark-printed','function_id'=>'Cetak barcode produk untuk putaway','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/purchase-returns/{id}','function_id'=>'Ambil detail retur pembelian','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/purchase-returns/unpaid/','function_id'=>'Ambil retur pembelian yang belum lunas','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'DELETE','endpoint'=>'/purchase/return-settlements/','function_id'=>'Hapus settlement retur pembelian','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/return-settlements/bills/','function_id'=>'Ambil semua settlement bill retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/return-settlements/bills/','function_id'=>'Buat/ubah settlement bill retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/return-settlements/bills/{id}','function_id'=>'Ambil detail settlement bill retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/return-settlements/refunds/','function_id'=>'Ambil semua refund settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'POST','endpoint'=>'/purchase/return-settlements/refunds/','function_id'=>'Buat/ubah refund settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/return-settlements/refunds/{id}','function_id'=>'Ambil detail refund settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Purchasing','method'=>'GET','endpoint'=>'/purchase/serial-number/wms/{bill_detail_id}','function_id'=>'Ambil nomor seri/batch item per bill detail','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/receive','function_id'=>'Cetak bill terima untuk purchase order','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/consign','function_id'=>'Cetak bill terima produk konsinyasi','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/invoice','function_id'=>'Cetak invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/lable/print/','function_id'=>'Cetak label pengiriman','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/purchaseorder/','function_id'=>'Cetak detail purchase order','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/stock-opname','function_id'=>'Cetak daftar item untuk opname','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/shipping-label/','function_id'=>'Cetak label pengiriman','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/wms/shipping-manifest','function_id'=>'Cetak bukti pengiriman (shipping manifest)','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/putaway','function_id'=>'Cetak laporan putaway','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/item-receive-notplace','function_id'=>'Cetak daftar item diterima yang belum diletakkan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/adjustment','function_id'=>'Cetak laporan penyesuaian stok','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/','function_id'=>'Ambil semua data penjualan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'DELETE','endpoint'=>'/sales/','function_id'=>'Hapus retur/invoice penjualan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/invoices/','function_id'=>'Ambil semua invoice penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/invoices/','function_id'=>'Buat/ubah invoice penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/invoices/for-return-wms/{contact_id}','function_id'=>'Ambil ID invoice untuk retur penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/invoices/{id}','function_id'=>'Ambil detail invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/invoices/overdue/','function_id'=>'Ambil invoice yang jatuh tempo','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/invoices/summary/','function_id'=>'Ambil ringkasan invoice per toko','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/invoices/unpaid/','function_id'=>'Ambil invoice yang belum lunas','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/orders/','function_id'=>'Buat/ubah sales order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'DELETE','endpoint'=>'/sales/orders/','function_id'=>'Hapus sales order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/orders/{id}','function_id'=>'Ambil detail sales order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/orders/cancel/','function_id'=>'Ambil sales order yang dibatalkan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/orders/delete-canceled','function_id'=>'Hapus item order yang dibatalkan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/orders/failed/','function_id'=>'Ambil sales order yang gagal','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/picklists/{picklist_id}','function_id'=>'Ambil item dalam picklist','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/orders/mark-as-complete','function_id'=>'Tandai sales order selesai','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/orders/returned-list/','function_id'=>'Ambil sales order yang diretur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/orders/save-airwaybill/','function_id'=>'Perbarui AWB sales order','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/orders/save-received-date','function_id'=>'Perbarui tanggal terima sales order','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/orders/set-as-paid','function_id'=>'Set sales order menjadi lunas','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/packlists/','function_id'=>'Ambil semua packlist','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/shipments/{shipment_header_id}','function_id'=>'Ambil item siap kirim per jadwal shipment','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/packlists/{id}','function_id'=>'Ambil detail packlist','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/packlists/create-invoice-payment','function_id'=>'Konversi sales order jadi invoice + pembayaran','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/packlists/create-invoice','function_id'=>'Konversi sales order menjadi invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/packlists/shipped/','function_id'=>'Ambil sales order yang sudah dikirim','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/payments/','function_id'=>'Ambil semua pembayaran invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/payments/','function_id'=>'Buat/ubah pembayaran invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'DELETE','endpoint'=>'/sales/payments/','function_id'=>'Hapus pembayaran invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/payments/{id}','function_id'=>'Ambil detail pembayaran invoice','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/picklists/items-to-pick','function_id'=>'Ambil daftar item untuk dipick','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'DELETE','endpoint'=>'/sales/picklists/to-ship/','function_id'=>'Hapus picklist','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/request-awb-order/','function_id'=>'Minta AWB untuk order','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/return-settlements/','function_id'=>'Ambil semua settlement retur penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'DELETE','endpoint'=>'/sales/return-settlements/','function_id'=>'Hapus settlement retur penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/return-settlements/invoices/','function_id'=>'Ambil semua invoice settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/return-settlements/invoices/','function_id'=>'Buat/ubah invoice settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/return-settlements/invoices/{id}','function_id'=>'Ambil detail invoice settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/return-settlements/refunds/','function_id'=>'Ambil semua refund settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/return-settlements/refunds/','function_id'=>'Buat/ubah refund settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/return-settlements/refunds/{id}','function_id'=>'Ambil detail refund settlement retur','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/returns/items/','function_id'=>'Ambil semua item retur','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/returns/items/unprocessed/wms','function_id'=>'Ambil retur penjualan yang belum diproses','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/returns/items/rejected/','function_id'=>'Ambil order retur yang ditolak','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/returns/items/resolved/','function_id'=>'Ambil order retur yang disetujui/selesai','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/sales-returns/','function_id'=>'Ambil semua retur penjualan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/sales-returns/','function_id'=>'Terima retur penjualan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/sales-returns/{id}','function_id'=>'Ambil detail retur penjualan','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/sales-returns/unpaid/','function_id'=>'Ambil retur penjualan yang belum lunas','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/settlements/','function_id'=>'Ambil semua settlement penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/settlements/{id}','function_id'=>'Ambil detail settlement penjualan','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/orders/change-location/','function_id'=>'Ubah lokasi gudang untuk order','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/shipments/orders/','function_id'=>'Buat order pengiriman (shipment)','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'GET','endpoint'=>'/sales/unfullfilled/','function_id'=>'Ambil packlist yang belum terpenuhi','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'GET','endpoint'=>'/shopee/logistics','function_id'=>'Ambil opsi logistik Shopee','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'GET','endpoint'=>'/store-locations/','function_id'=>'Ambil lokasi toko','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'GET','endpoint'=>'/systemsetting/account-mapping','function_id'=>'Ambil pemetaan akun akuntansi','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'GET','endpoint'=>'/systemsetting/users/','function_id'=>'Ambil daftar user/staf gudang','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'POST','endpoint'=>'/systemsetting/webhook','function_id'=>'Buat/ubah registrasi webhook','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'GET','endpoint'=>'/lazada/get-shipment-providers/{storeId}/','function_id'=>'Ambil info penyedia pengiriman Lazada','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Reports','method'=>'GET','endpoint'=>'/reports/wms/pick-list','function_id'=>'Cetak picklist item','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/order/getOrderByNo/','function_id'=>'Ambil sales order yang itemnya akan dipick','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/shipments/get-order/','function_id'=>'Perbarui qty item yang sudah diserahkan ke kurir','status'=>'todo','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/shipments/','function_id'=>'Set item sudah diterima kurir','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Sales','method'=>'POST','endpoint'=>'/sales/picklists/items-to-pick/','function_id'=>'Ambil daftar item untuk dipick (varian)','status'=>'in_progress','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/picklists/','function_id'=>'Buat picklist / set picklist selesai','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'WMS (Warehouse Management System)','method'=>'POST','endpoint'=>'/wms/sales/packlist','function_id'=>'Buat packlist','status'=>'done','pic'=>'Rasyid','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'System Setting','method'=>'GET','endpoint'=>'/taxes/','function_id'=>'Ambil daftar pajak','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product Listing','method'=>'GET','endpoint'=>'/tokopedia/showcases','function_id'=>'Ambil etalase (showcase) Tokopedia','status'=>'todo','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Product','method'=>'GET','endpoint'=>'/variations','function_id'=>'Ambil semua variasi (variant) produk','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/invoice','function_id'=>'Webhook: notifikasi invoice baru','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/payment','function_id'=>'Webhook: notifikasi update pembayaran','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/price','function_id'=>'Webhook: notifikasi update harga','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/product','function_id'=>'Webhook: notifikasi produk baru','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/purchaseorder','function_id'=>'Webhook: notifikasi PO baru','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/salesorder','function_id'=>'Webhook: notifikasi update sales order','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/salesreturn','function_id'=>'Webhook: notifikasi retur penjualan baru','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/stock','function_id'=>'Webhook: notifikasi update stok','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Webhooks','method'=>'POST','endpoint'=>'/webhooks/stocktransfer','function_id'=>'Webhook: notifikasi transfer stok baru','status'=>'done','pic'=>'Darriel','priority'=>null,'source'=>'jubelio'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E1. Sales Invoice + Payment + Settlement','function_id'=>'Epik untuk domain Sales','status'=>'todo','pic'=>'Rasyid','priority'=>'P0','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E2. Purchase Bill + Payment + Return + Settlement','function_id'=>'Epik untuk domain Purchasing','status'=>'todo','pic'=>'Rasyid','priority'=>'P0','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E3. Contact terpadu (customers/suppliers)','function_id'=>'Epik untuk domain Contact','status'=>'todo','pic'=>'Rasyid','priority'=>'P0','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E4. Finance: Journal + Accounts (CoA)','function_id'=>'Epik untuk domain Journal','status'=>'todo','pic'=>'Darriel','priority'=>'P1','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E5. Cash & Bank','function_id'=>'Epik untuk domain Cash & Bank','status'=>'todo','pic'=>'Darriel','priority'=>'P1','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E6. Tax lengkap','function_id'=>'Epik untuk domain System Setting','status'=>'todo','pic'=>'Darriel','priority'=>'P1','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E7. Reports (PDF/print)','function_id'=>'Epik untuk domain Reports','status'=>'todo','pic'=>'Rasyid','priority'=>'P1','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E8. Webhooks outbound','function_id'=>'Epik untuk domain Webhooks','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E9. Marketplace: Shopee, Tokopedia, Lazada, Blibli','function_id'=>'Epik untuk domain Channels','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E10. Inventory extended (promotions, price-list, bundles, dst)','function_id'=>'Epik untuk domain Inventory','status'=>'todo','pic'=>'Rasyid','priority'=>'P3','source'=>'epic'],
            ['domain'=>'Epic','method'=>null,'endpoint'=>'E11. System Setting (account-mapping, return-setting, dst)','function_id'=>'Epik untuk domain System Setting','status'=>'todo','pic'=>'Darriel','priority'=>'P3','source'=>'epic'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — OAuth / Auth toko','function_id'=>'Integrasi OAuth / Auth toko untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Manajemen toko (list/refresh token)','function_id'=>'Integrasi Manajemen toko (list/refresh token) untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Tarik order (pull)','function_id'=>'Integrasi Tarik order (pull) untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Terima/tolak order','function_id'=>'Integrasi Terima/tolak order untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Push produk (create listing)','function_id'=>'Integrasi Push produk (create listing) untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Sync produk (update)','function_id'=>'Integrasi Sync produk (update) untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Sync stok (push balik)','function_id'=>'Integrasi Sync stok (push balik) untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Sync harga','function_id'=>'Integrasi Sync harga untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Webhook masuk','function_id'=>'Integrasi Webhook masuk untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Cancel order','function_id'=>'Integrasi Cancel order untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Shopee — Logistik / kurir channel','function_id'=>'Integrasi Logistik / kurir channel untuk Shopee (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — OAuth / Auth toko','function_id'=>'Integrasi OAuth / Auth toko untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Manajemen toko (list/refresh token)','function_id'=>'Integrasi Manajemen toko (list/refresh token) untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Tarik order (pull)','function_id'=>'Integrasi Tarik order (pull) untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Terima/tolak order','function_id'=>'Integrasi Terima/tolak order untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Push produk (create listing)','function_id'=>'Integrasi Push produk (create listing) untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Sync produk (update)','function_id'=>'Integrasi Sync produk (update) untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Sync stok (push balik)','function_id'=>'Integrasi Sync stok (push balik) untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Sync harga','function_id'=>'Integrasi Sync harga untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Webhook masuk','function_id'=>'Integrasi Webhook masuk untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Cancel order','function_id'=>'Integrasi Cancel order untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Tokopedia — Logistik / kurir channel','function_id'=>'Integrasi Logistik / kurir channel untuk Tokopedia (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — OAuth / Auth toko','function_id'=>'Integrasi OAuth / Auth toko untuk Lazada (pola TikTok)','status'=>'done','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Manajemen toko (list/refresh token)','function_id'=>'Integrasi Manajemen toko (list/refresh token) untuk Lazada (pola TikTok)','status'=>'done','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Tarik order (pull)','function_id'=>'Integrasi Tarik order (pull) untuk Lazada (pola TikTok)','status'=>'done','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Terima/tolak order','function_id'=>'Integrasi Terima/tolak order untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Push produk (create listing)','function_id'=>'Integrasi Push produk (create listing) untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Sync produk (update)','function_id'=>'Integrasi Sync produk (update) untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Sync stok (push balik)','function_id'=>'Integrasi Sync stok (push balik) untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Sync harga','function_id'=>'Integrasi Sync harga untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Webhook masuk','function_id'=>'Integrasi Webhook masuk untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Cancel order','function_id'=>'Integrasi Cancel order untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Lazada — Logistik / kurir channel','function_id'=>'Integrasi Logistik / kurir channel untuk Lazada (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — OAuth / Auth toko','function_id'=>'Integrasi OAuth / Auth toko untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Manajemen toko (list/refresh token)','function_id'=>'Integrasi Manajemen toko (list/refresh token) untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Tarik order (pull)','function_id'=>'Integrasi Tarik order (pull) untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Terima/tolak order','function_id'=>'Integrasi Terima/tolak order untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Push produk (create listing)','function_id'=>'Integrasi Push produk (create listing) untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Sync produk (update)','function_id'=>'Integrasi Sync produk (update) untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Sync stok (push balik)','function_id'=>'Integrasi Sync stok (push balik) untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Sync harga','function_id'=>'Integrasi Sync harga untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Webhook masuk','function_id'=>'Integrasi Webhook masuk untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Cancel order','function_id'=>'Integrasi Cancel order untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
            ['domain'=>'Omnichannel','method'=>null,'endpoint'=>'Blibli — Logistik / kurir channel','function_id'=>'Integrasi Logistik / kurir channel untuk Blibli (pola TikTok)','status'=>'todo','pic'=>'Darriel','priority'=>'P2','source'=>'omnichannel'],
        ];
    }
}
