services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: staging-superapp-dev
    container_name: staging-superapp
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
