# Menggunakan fitur YAML Anchor agar config tidak ditulis berulang-ulang
x-app-config: &app-config
  image: ghcr.io/ultra-teknologi-indonesia/cilupbah:${CILUPBAH_IMAGE_TAG:-latest}
  restart: unless-stopped
  environment:
    - APP_ENV=staging
    - APP_DEBUG=false
    - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/var/www/html/docker/php
  depends_on:
    - redis
    - pgsql
  volumes:
    # Mount file .env langsung ke root aplikasi di dalam container
    - ./.env:/var/www/html/.env
    # Mount folder yang isinya berubah/dinamis di production
    - ./storage/app:/var/www/html/storage/app
    - ./storage/framework:/var/www/html/storage/framework
    - ./storage/logs:/var/www/html/storage/logs
    - ./bootstrap/cache:/var/www/html/bootstrap/cache

services:
  app:
    <<: *app-config
    container_name: cilupbah-staging
    entrypoint: [ "/usr/local/bin/start.staging.sh" ]
    ports:
      - "8002:8000"

  horizon:
    <<: *app-config
    container_name: cilupbah-staging-horizon
    entrypoint: [ "php", "artisan", "horizon" ]

  scheduler:
    <<: *app-config
    container_name: cilupbah-staging-scheduler
    entrypoint: [ "php", "artisan", "schedule:work" ]

  redis:
    container_name: cilupbah-staging-redis
    image: redis:7-alpine
    restart: unless-stopped
    command:
      - redis-server
      - --maxmemory
      - "512mb"
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - ""
      - --appendonly
      - "no"
    volumes:
      - staging_redisdata:/data

  pgsql:
    container_name: cilupbah-staging-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: cilupbah_staging
      POSTGRES_USER: user_staging
      POSTGRES_PASSWORD: password_staging
    volumes:
      - staging_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Diekspos ke port 5433 di host agar tidak bentrok jika host punya postgres

volumes:
  staging_redisdata:
  staging_pgdata:
