<?php

namespace Modules\Outbound\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Outbound\Models\Courier;

/**
 * Production-safe seeder untuk master data Courier (kurir/ekspedisi).
 *
 * Karakteristik:
 * - Idempotent: aman dijalankan berkali-kali. Baris yang sudah ada (match by code)
 *   tidak akan disentuh; baris baru diinsert.
 * - Global (tenant_id = null): kurir muncul di list global. Untuk skema per-tenant,
 *   duplikasi record per tenant harus dilakukan dengan seeder lain.
 * - Kode di-generate deterministik dari nama (slug uppercase). Bentrok
 *   diselesaikan dengan suffix `_2`, `_3`, dst.
 *
 * Cara jalan (production):
 *   php artisan module:seed Outbound --class=CourierSeeder
 * atau via DB seeder root:
 *   php artisan db:seed --class="Modules\\Outbound\\Database\\Seeders\\CourierSeeder"
 */
class CourierSeeder extends Seeder
{
    public function run(): void
    {
        $names = $this->courierNames();

        DB::transaction(function () use ($names) {
            foreach ($names as $name) {
                $normalized = trim($name);
                if ($normalized === '') {
                    continue;
                }

                $code = $this->uniqueCodeFor($normalized);

                Courier::firstOrCreate(
                    ['code' => $code],
                    [
                        'name'                     => $normalized,
                        'type'                     => 'REGULAR',
                        'tracking_url'             => null,
                        'logo_url'                 => null,
                        'is_active'                => true,
                        'supported_shipment_types' => null,
                        'metadata'                 => null,
                        'tenant_id'                => null,
                    ]
                );
            }
        });
    }

    private function uniqueCodeFor(string $name): string
    {
        $base = $this->makeCode($name);
        $code = $base;
        $i = 2;

        while (
            Courier::where('code', $code)
                ->where('name', '!=', $name)
                ->exists()
        ) {
            $code = $base . '_' . $i;
            $i++;
        }

        return $code;
    }

    private function makeCode(string $name): string
    {
        $slug = @iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $name);
        if ($slug === false || $slug === '') {
            $slug = $name;
        }

        $slug = strtoupper($slug);
        $slug = preg_replace('/[^A-Z0-9]+/', '_', $slug) ?? '';
        $slug = trim($slug, '_');

        if ($slug === '') {
            $slug = 'COURIER_' . strtoupper(substr(md5($name), 0, 8));
        }

        if (strlen($slug) > 120) {
            $slug = substr($slug, 0, 100) . '_' . strtoupper(substr(md5($name), 0, 8));
        }

        return $slug;
    }

    /**
     * @return string[]
     */
    private function courierNames(): array
    {
        return [
            'Anteraja Economy',
            'Jago Pack',
            'Kurir Rekomendasi',
            'Lion Parcel JAGOPACK',
            'ACC LOGISTIK',
            'DUTA TRANS',
            'Warrior Cargo',
            'Warrior Express',
            'RAYSPEED',
            'INTERNAL',
            'OEXPRESS',
            'J&T REG',
            'J&T Express EZ',
            'J&T DFOD',
            'Pos Kilat Khusus',
            'Pos Express Next Day Service',
            'GO-SEND Same Day',
            'GO-SEND Instant',
            'Grab Parcel Reguler',
            'Grab Parcel Next Day',
            'Grab Parcel Same Day',
            'Grab Instant',
            'JNE REG',
            'JNE YES',
            'JNE OKE',
            'JNE Trucking',
            'TIKI Reg',
            'TIKI ONS',
            'NINJA REG',
            'NINJA FAST',
            'Wahana Tarif Normal',
            'Grab Sameday',
            'SiCepat REG',
            'SiCepat BEST',
            'Kirim Sendiri',
            'Laris Cargo',
            'Mex Berlian',
            'Herona Express',
            'Indah Cargo',
            'Spx',
            'Hyra',
            'Raya Kita',
            'Sentral Cargo',
            'Red Ex',
            'Karunia Indah 8 (KI8)',
            'Sinar Shuttle',
            'Antar Aja',
            'Sinar Trans Express',
            'Speedy',
            'RCL (Red Carpet Logistics)',
            'Etobee',
            'Alfatrex',
            'JX',
            'Pos Jumbo Ekonomi',
            'ID Express',
            'Ambil Sendiri',
            'Teba',
            'KALOG created',
            'GOJEK',
            'Pickup: NinjaVanID, Delivery: Ninja Van MP',
            'Pickup: Gojek, Delivery: Go-Jek MP',
            'LEL EXPRESS',
            'Travel',
            'Cargo',
            'Bus',
            'Kereta',
            'SicepatHalu',
            'JX Standart',
            'C²',
            'J&T Express',
            'Kurir Toko ST-Toms',
            'Dakota Cargo',
            'JNE YES (CASHLESS)',
            'JNE REGULER (CASHLESS)',
            'Maju Bersama',
            'Wira Agung',
            'Sajira',
            'JNT Drop Off Non Online Booking',
            'J&T Economy',
            'SiCepat GOKIL',
            'LEX MP',
            'Sicepat Siuntung',
            'Sicepat Cargo',
            'Kurir Toko',
            'Naga Lintas',
            'TIKI Ekonomi',
            'Shopee Express',
            'JNE COD',
            'JNE NON COD',
            'PAXEL',
            'Anteraja Same Day',
            'J&T COD',
            'Anteraja Next Day',
            'Anteraja Reguler',
            'Buana Raya Express',
            'REX-10 - REX',
            'Micro',
            'HD-Express',
            'Hira',
            'JNT Cashless',
            'MPS',
            'AJU-EXPRESS',
            'Ambil Sendiri di PT Behaestex (Khusus Gresik)',
            'SAP EKSPRESS - DFOD ',
            'Mail Express',
            'ID DFOD',
            'J&T Cargo',
            'Baraka',
            'Nusantara',
            'SAP Express - SAME DAY SERVICE',
            'SAP Express - REGULER',
            'SAP Express - REGULAR DARAT',
            'SAP Express - REGULAR LAUT',
            'SAP Express - CITY REGULAR',
            'SAP Express - CITY URGENT',
            'SAP Express - TRUCKING',
            'SAP Express - ONE DAY SERVICE (CREDIT CARD)',
            'SAP Express - ATM',
            'Merpati',
            'Angkunas',
            'Gocar',
            'TIKI SDS',
            'Ambil ke toko',
            'Ambil ke pabrik',
            'LION COD',
            'Maxim',
            'Merpati Travel',
            'Hira Logistic',
            'CMC',
            'Pelunasan Shopee',
            'Custom Logistik Service Normal',
            'SiCepat Cashless',
            'Deliveree',
            'Panca Jaya',
            'Adam',
            'Duta Cargo',
            'Anteraja Regular',
            'Paxel Sameday',
            'Paxel Instant',
            'Paxel Big',
            'POS EMS',
            'MKS',
            'HWU',
            'Cinta Saudara',
            'BNE',
            'JAGO EXPRESS',
            'RAX CARGO',
            'KBI - EXPEDISI KERETA',
            'ACC CARGO',
            'MEDIA LOGISTIK',
            'NASRU',
            'Gosend Instant',
            'Gosend SameDay',
            'J-Express',
            'Ninja Sameday',
            'Ninja Nextday',
            'Ninja Express',
            'Ninja Standard',
            'Grab Express Instant',
            'Grab Express Sameday',
            'Kerry Express',
            'ID Express Standard',
            'ID Express Sameday',
            'ID Express Truck',
            'JNE DFOD',
            'JNE CTC',
            'Jaya Express',
            'Samas Express',
            'Agung',
            'Berkat',
            'Lion Parcel REGPACK',
            'Lion Parcel ONEPACK',
            'Lion Parcel BIGPACK',
            'NWF AJH',
            'TIKI Trucking ',
            'LSJ Express',
            'Pickup: LEX ID, Delivery: LEX ID',
            'Wahana Ekonomi',
            'LION - Jagopack',
            'LIOON - Regpack',
            'MEX',
            'MKS BERKAT MAJU JAYA',
            'SUMBER URIP CARGO',
            'AGUNG PRIMA',
            'MULIO CITRA ANGKASA',
            'RPX PAS SameDay',
            'RPX PAS NextDay',
            'RPX PAS Regular',
            'RPX PAS Economy',
            'SRIWIJAYA PRIMA',
            'RPX PAS Heavy Weight',
            'NUSANTARA EXPRESS',
            'Sicepat DFOD',
            'CMC Express',
            'Lalamove',
            'Custom Courier',
            'SINAR JAYA',
            'Virgotrans Surabaya',
            'CV. Alwi Jaya Transport',
            'JNE OKE COD ONGKIR',
            'JNE REG COD ONGKIR',
            'JNE JTR COD ONGKIR',
            'Sentral Cargo Udara',
            'Sentral Cargo Darat',
            'Depo Samas Surabaya',
            'Sinar Mandiri Cepat',
            'Amalindo Indonesia',
            'Olympic Abadi (PT. Angkasa Dirga Mandiri)',
            'Ekspedisi Transpapua',
            'PT. Soekini',
            'Riona Cargo',
            'Papandayan Cargo',
            'Ekspedisi Margomulyo Baru',
            'Cipta Maju',
            'Kresna Jaya Ekspedisi',
            'Trobos Ekspedisi',
            'Putra Bengawan',
            'PT. Arthalapan Strategi Logistik',
            'Anugerah Selamat Sejahtera',
            'PT. Angkutan Utama Perkasa',
            'Dot Ekspres',
            'Timbul Jaya',
            'Maju Express',
            'Citra Express',
            'Ekspedisi Cokro',
            'Ambra Logistik',
            'ABC TRANSPORT',
            'ADAM JAYA SAKTI',
            'ALKEN LINES',
            'AMAN SAMUDERA',
            'ANEKA LOGISTIK',
            'ANGKASA DIRGAMANDIRI',
            'AR KARYATI',
            'ARIFIN DIRGANTARA',
            'ARMADA JAYA',
            'ASM EKSPEDISI',
            'ATOM MULTI A',
            'ANTARIKSA ANTARNUSA',
            'BALI PRIMA',
            'BANYUWANGI CEPAT',
            'BARAKA SARANA TAMA',
            'BERKAH CAHAYA TRANS',
            'BERKAT SEJATI',
            'BINA USAHA',
            'BINTANG MAS',
            'BUANA RAYA EKSPRES',
            'BUANA LANGGENG JAYA',
            'BUANA TRAVEL',
            'CANDRA DEWI',
            'CATUR MANDIRITAMA',
            'CKB CARGO',
            'DAKOGA BUANA SEMESTA',
            'DEPO SPILL',
            'DEPO TEMAS',
            'DEWATA LINTAS JAYA',
            'DINOYO BARU BERSATU',
            'DINOYO PUTRA',
            'ATLAS',
            'DAMAI',
            'FAJAR',
            'GLOBAL',
            'HASIL BUNI',
            'HERONA',
            'JAYA MULYA',
            'KARTIKA',
            'KS',
            'KRISNA JAYA',
            'MEGA EXPRESS',
            'MEKAR JAYA',
            'MERDEKA',
            'PODO HASIL',
            'PRISMA CARGO',
            'RIZKI AGUNG',
            'SUMBER AGUNG',
            'SUMBER SARI',
            'TRIJAYA LINTAS',
            'MULYA BAKTI',
            'LESTARI',
            'LIMA JAYA',
            'KWK',
            'EMS KERETA API',
            'EMS TRUCK',
            'PERSADA MULIA',
            'MULTI JAYA',
            'AMAN SURYA NUSA',
            'GARUDA LINTAS',
            'MUTIARA',
            'PANDUSIWI',
            'KALIMAS',
            'PAHALA KEBCANA',
            'DELTA',
            'FIRST LOGISTIK',
            'GARUDA LINTAS BORNEO',
            'GENDHIS',
            'HARAPAN JAYA',
            'JAVA EXPRESS',
            'JAYA MAS SURABAYA',
            'KM INDAH',
            'KARYATI',
            'KRESNA',
            'PRIMA JASA ABADI',
            'SAKURA EXPRES',
            'SARANA UTAMA CARGO',
            'STAR CARGO',
            'SUBOKA PRATAMA',
            'SUMBER BARU',
            'SULUNG',
            'TRIJAYA',
            'TRIWARNO',
            'YUDA PERKASA',
            'DIKIRIM PENJUAL',
            'Auto Cargo',
            'SPX Standard',
            'SPX Hemat',
            'Agen SPX Express',
            'PCP Regular',
            'PEXPRESS',
            'RAYSPEED - SG (REG)',
            'RAYSPEED - MY',
            'Kobra',
            'SPX Instant',
            'kurir 4848',
            "D'SEA LOGISTIC",
            'SEGARA',
            'Bariz',
            'LNP',
            'DRATRANS',
            'J&T JND',
            'Rayspeed Asia',
            'Gemilang Asri Maju',
            'UBZR',
            'Naga Lintas Wahid',
            'Trijasa Jaya Utama',
            'Kedaton Jaya',
            'Karunia Cipta Logistic',
            'Exp Sindo',
            'AN Putra Transport',
            'Pasific Jaya Express',
            'GoTo Logistics GTL Standard',
            'FREE',
            'Ninja Cargo',
            'CNT Cargo',
            'KIA Cargo',
            'SHP Cargo',
            'Berkat Abadi Jaya',
            'Jaya Alam Laksana',
            'SAHABAT BELITUNG EXPRESS',
            'Jago Jaya Express',
            'Mitra Wibowo',
            'HImeji',
            'DMX Cargo',
            'New Putra Duta',
            'SDR',
            'Express Jaya Gemilang',
            'Tritunggal Jakarta',
            'TLX Rajawali',
            'Tam Cargo',
            'Blitz Marketplace',
            'Rahayu Express',
            'Charter Pick-Up',
            'Armada Pabrik',
            'Armada Pratama',
            'Al-Kafii Cargo',
            'Muat Cargo',
            '21 Express',
            'LJR',
            'Pickup in Pusat',
            'RM Express',
            'RM Ekspress',
            'Lion Parcel BOSSPACK',
            'Lintas Abadi',
            'Pegasus',
            'Malaysia',
            'Acm',
            'LAKUSIX NEW',
            'Den Logistik',
            'J&T HBO',
            'Triadhipa Logistics',
            'Lion INTERPACK',
            'Multi Express',
            'Teman Express',
            'Berkat Maju Sentosa',
            'Karuna Travel',
            'NN Mandiri',
            'DSS',
            'Terang Bersaudara Kapuk',
            'Tri Tunggal',
            'Sinar Dagang',
            'Sinar Jaya Ekspedisi',
            'Meta Baru Kapuk',
            'Sumber Urip',
            'Karya Agung',
            'Mulio Angkasa',
            'Graha Mas Kapuk',
            'Cosmos Pusat',
            'Merah Jaya',
            'Berkat Maju Jaya',
            'Agung Mabes',
            'Nirmala Sunter',
            'Blitz-ID INSTANT',
            'Ekspedisi Lintas Jawa-Sumatra',
            'Titian Mas',
        ];
    }
}
