<?php

namespace Modules\Product\Support;

class ChannelSku
{

    /**
     * Internal bundle variants are implementation details, never seller SKUs.
     */
    public static function isTechnicalBundleSku($value): bool
    {
        $sku = trim((string) ($value ?? ''));

        return str_starts_with(mb_strtolower($sku), '__bundle__')
            && mb_strlen($sku) > mb_strlen('__bundle__');
    }

    public static function normalize($value, ?string $externalProductId = null): ?string
    {
        $sku = trim((string) ($value ?? ''));

        if ($sku === '' || self::isTechnicalBundleSku($sku) || preg_match('/[\p{L}\p{N}]/u', $sku) !== 1) {
            return null;
        }

        if (self::isAutoGenerated($sku, $externalProductId)) {
            return null;
        }

        return $sku;
    }

    public static function isPlaceholder($value, ?string $externalProductId = null): bool
    {
        return self::normalize($value, $externalProductId) === null;
    }

    public static function reason($value, ?string $externalProductId = null): ?string
    {
        $sku = trim((string) ($value ?? ''));

        if ($sku === '') {
            return 'Model tidak punya SKU di channel — isi SKU di Seller Center agar bisa dipetakan.';
        }

        if (self::isTechnicalBundleSku($sku)) {
            return 'SKU teknis internal bundle ("' . $sku . '") tidak boleh dipakai sebagai SKU channel — isi SKU penjual asli di Seller Center.';
        }

        if (preg_match('/[\p{L}\p{N}]/u', $sku) !== 1) {
            return 'SKU model hanya berisi tanda baca ("' . $sku . '") — isi SKU asli di Seller Center agar bisa dipetakan.';
        }

        if (self::isAutoGenerated($sku, $externalProductId)) {
            return 'SKU model dibuat otomatis marketplace ("' . $sku . '") karena kosong di Seller Center — isi SKU asli agar bisa dipetakan.';
        }

        return null;
    }

    private static function isAutoGenerated(string $sku, ?string $externalProductId): bool
    {
        $listingId = trim((string) $externalProductId);

        if ($listingId === '') {
            return false;
        }

        return preg_match('/^' . preg_quote($listingId, '/') . '-[\d-]+$/', $sku) === 1;
    }
}
