apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cilupbah-staging

type: Opaque

stringData:
  TIKTOK_APP_KEY:
  TIKTOK_APP_SECRET:

  LAZADA_APP_KEY: 139423
  LAZADA_APP_SECRET:

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

  SHOPEE_PARTNER_ID: 1236178
  SHOPEE_PARTNER_KEY:
  SHOPEE_PUSH_PARTNER_KEY:

  MAIL_USERNAME: null
  MAIL_PASSWORD: null
