<?php

use App\Http\Middleware\HorizonBasicAuth;
use Illuminate\Support\Str;

return [

    'name' => env('HORIZON_NAME'),

    'domain' => env('HORIZON_DOMAIN'),

    'path' => env('HORIZON_PATH', 'horizon'),

    'use' => env('HORIZON_REDIS_CONNECTION', 'default'),

    'prefix' => env(
        'HORIZON_PREFIX',
        Str::slug(env('APP_NAME', 'laravel'), '_').'_horizon:'
    ),

    'middleware' => ['web', HorizonBasicAuth::class],

    'allowed_emails' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('HORIZON_ALLOWED_EMAILS', ''))
    ))),

    'waits' => [
        'redis:default' => 60,
        'redis:tracking' => 60,
        'redis:channel-cancellation' => 30,
        'redis:channel-stock' => 60,
        config('queue.routing.stock_critical.connection', 'redis').':'
            .config('queue.routing.stock_critical.queue', 'stock-critical') => 30,
        config('queue.routing.stock_default.connection', 'redis').':'
            .config('queue.routing.stock_default.queue', 'stock-default') => 120,
        config('queue.routing.channel_finance.connection', 'redis-finance').':'
            .config('queue.routing.channel_finance.queue', 'channel-finance') => 120,
        'redis:channel-fulfillment' => 60,
        'redis-long:channel-product' => 120,
        'redis-long:channel-after-sales' => 120,
        'redis-long:stock-cutover' => 300,
        'redis-long:order-cutover' => 300,
        'redis-long:qr-labels' => 300,
    ],

    'trim' => [

        'recent' => 15,
        'pending' => 30,
        'completed' => 15,
        'recent_failed' => 720,
        'failed' => 1440,
        'monitored' => 720,
    ],

    'silenced' => [

    ],

    'silenced_tags' => [

    ],

    'metrics' => [
        'trim_snapshots' => [
            'job' => 24,
            'queue' => 24,
        ],
    ],

    'notifications' => [
        'slack_webhook' => env('HORIZON_SLACK_WEBHOOK'),
        'slack_channel' => env('HORIZON_SLACK_CHANNEL'),
        'mail' => env('HORIZON_MAIL_TO'),
    ],

    'fast_termination' => false,

    'memory_limit' => 192,

    'defaults' => [
        'supervisor-default' => [
            'connection' => 'redis',
            'queue' => [env('WEBHOOK_QUEUE', 'webhooks'), 'default', 'notifications', 'failed-jobs'],

            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxTime' => 3600,
            'maxJobs' => 250,
            'memory' => 128,
            'tries' => 1,
            'timeout' => 60,
            'nice' => 0,
        ],

        'supervisor-order-operations' => [
            'connection' => 'redis',
            'queue' => ['orders', 'fulfillment', 'stock-sync'],
            'balance' => 'off',
            'minProcesses' => 2,
            'maxProcesses' => 2,
            'maxTime' => 3600,
            'maxJobs' => 250,
            'timeout' => 60,
            'tries' => 3,
            'backoff' => [5, 15, 30],
            'memory' => 192,
            'nice' => 0,
        ],
        'supervisor-channel-sync' => [
            'connection' => config('queue.routing.channel_sync.connection', 'redis-channel-sync'),
            'queue' => [env('QUEUE_NAME_CHANNEL_SYNC', 'channel-sync'), env('QUEUE_NAME_PRODUCT', 'product')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxTime' => 3600,
            'maxJobs' => 250,
            'timeout' => 270,
            'tries' => 1,
            'backoff' => [5, 15, 30],
            'memory' => 192,
            'nice' => 0,
        ],

        'supervisor-channel-operations' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_CHANNEL_CANCELLATION', 'channel-cancellation'),
                env('QUEUE_NAME_CHANNEL_STOCK', 'channel-stock'),
                env('QUEUE_NAME_CHANNEL_FULFILLMENT', 'channel-fulfillment'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'maxTime' => 1800,
            'timeout' => 60,
            'tries' => 3,
            'backoff' => [10, 30, 60],
            'memory' => 128,
            'nice' => 0,
        ],
        'supervisor-channel-finance' => [
            'connection' => config('queue.routing.channel_finance.connection', 'redis-finance'),
            'queue' => [config('queue.routing.channel_finance.queue', 'channel-finance')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 100,
            'maxTime' => 1800,
            'timeout' => 240,
            'tries' => 3,
            'backoff' => [30, 120, 300],
            'memory' => 256,
            'nice' => 5,
        ],
        'supervisor-channel-product' => [
            'connection' => config('queue.routing.channel_product.connection', 'redis-long'),
            'queue' => [config('queue.routing.channel_product.queue', 'channel-product')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 100,
            'maxTime' => 1800,
            'timeout' => 330,
            'tries' => 3,
            'backoff' => [30, 120, 300],
            'memory' => 256,
            'nice' => 10,
        ],
        'supervisor-channel-after-sales' => [
            'connection' => config('queue.routing.channel_after_sales.connection', 'redis-long'),
            'queue' => [config('queue.routing.channel_after_sales.queue', 'channel-after-sales')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 100,
            'maxTime' => 1800,
            'timeout' => 150,
            'tries' => 5,
            'backoff' => [30, 120, 300, 600, 1200],
            'memory' => 256,
            'nice' => 0,
        ],
        'supervisor-cutover' => [
            'connection' => config('operations.stock_cutover_console.queue_connection', 'redis-long'),

            'queue' => [
                config('operations.stock_cutover_console.queue', 'stock-cutover'),
                config('operations.order_cutover_console.queue', 'order-cutover'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 1,
            'maxTime' => 1800,
            'timeout' => 1800,
            'tries' => 1,
            'backoff' => [60, 300, 900],
            'memory' => 1024,
            'nice' => 10,
        ],
        'supervisor-stock' => [
            'connection' => config('queue.routing.stock_critical.connection', 'redis'),
            'queue' => [
                config('queue.routing.stock_critical.queue', 'stock-critical'),
                config('queue.routing.stock_default.queue', 'stock-default'),
            ],
            'balance' => 'off',

            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxTime' => 3600,
            'maxJobs' => 250,
            'timeout' => 60,
            'tries' => 3,
            'backoff' => [3, 10, 30],
            'memory' => 128,
            'nice' => 0,
        ],
        'supervisor-downloads' => [
            'connection' => 'redis-long',
            'queue' => ['downloads'],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 100,
            'timeout' => 900,
            'tries' => 3,
            'backoff' => [10, 30, 60],
            'memory' => 256,
            'nice' => 0,
        ],
        'supervisor-labels' => [
            'connection' => config('queue.routing.labels.connection', 'redis-long'),
            'queue' => [config('queue.routing.labels.queue', 'labels')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 100,
            'timeout' => 600,
            'tries' => 1,
            'memory' => 512,
            'nice' => 0,
        ],
        'supervisor-qr-labels' => [
            'connection' => config('queue.routing.qr_labels.connection', 'redis-long'),
            'queue' => [config('queue.routing.qr_labels.queue', 'qr-labels')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 20,
            'timeout' => 1800,
            'tries' => 1,
            'memory' => 512,
            'nice' => 5,
        ],
        'supervisor-tracking' => [
            'connection' => 'redis',
            'queue' => [config('queue.names.tracking', 'tracking')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 2,
            'backoff' => [10, 60],
            'memory' => 128,
            'nice' => 5,
        ],

        // Order dari setiap channel adalah failure domain terpisah. Error atau
        // lonjakan Shopee tidak boleh menahan order TikTok maupun Lazada.
        'supervisor-shopee-orders' => [
            'connection' => 'redis',
            'queue' => [config('queue.names.shopee_orders', 'shopee-orders')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 128,
            'nice' => 0,
        ],
        'supervisor-tiktok-orders' => [
            'connection' => 'redis',
            'queue' => [config('queue.names.tiktok_orders', 'tiktok-orders')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 128,
            'nice' => 0,
        ],
        'supervisor-lazada-orders' => [
            'connection' => 'redis',
            'queue' => [config('queue.names.lazada_orders', 'lazada-orders')],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 128,
            'nice' => 0,
        ],
        'supervisor-tiktok-webhooks-operational' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_TIKTOK_PACKAGES', 'tiktok-packages'),
                env('QUEUE_NAME_TIKTOK_WEBHOOKS', 'tiktok-webhooks'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 192,
            'nice' => 0,
        ],
        'supervisor-tiktok-webhooks-background' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_TIKTOK_AFTERSALES', 'tiktok-aftersales'),
                env('QUEUE_NAME_TIKTOK_CATALOG', 'tiktok-catalog'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 128,
            'nice' => 5,
        ],
        'supervisor-shopee-webhooks-operational' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_SHOPEE_TRACKING', 'shopee-tracking'),
                env('QUEUE_NAME_SHOPEE_WEBHOOKS', 'shopee-webhooks'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 192,
            'nice' => 0,
        ],
        'supervisor-shopee-webhooks-background' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_SHOPEE_AFTERSALES', 'shopee-aftersales'),
                env('QUEUE_NAME_SHOPEE_CATALOG', 'shopee-catalog'),
                env('QUEUE_NAME_WEBHOOK_DOWNLOADS', 'webhook-downloads'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 128,
            'nice' => 5,
        ],
        'supervisor-lazada-webhooks-operational' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_LAZADA_FULFILLMENT', 'lazada-fulfillment'),
                env('QUEUE_NAME_LAZADA_WEBHOOKS', 'lazada-webhooks'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 192,
            'nice' => 0,
        ],
        'supervisor-lazada-webhooks-background' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME_LAZADA_AFTERSALES', 'lazada-aftersales'),
                env('QUEUE_NAME_LAZADA_CATALOG', 'lazada-catalog'),
            ],
            'balance' => 'off',
            'minProcesses' => 1,
            'maxProcesses' => 1,
            'maxJobs' => 250,
            'timeout' => 120,
            'tries' => 3,
            'backoff' => [10, 60, 300],
            'memory' => 128,
            'nice' => 5,
        ],
    ],

    'environments' => [

        'production' => [],
        'staging' => [],
        'local' => [],
    ],

    'watch' => [
        'app',
        'bootstrap',
        'config/**/*.php',
        'database/**/*.php',
        'public/**/*.php',
        'resources/**/*.php',
        'routes',
        'composer.lock',
        'composer.json',
        '.env',
    ],
];
